server:
  port: 7004
#数据源配置好
spring:
  profiles:
    include: sharding
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.66:3306/gmall_order?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#  rabbitmq:
#    username: admin
#    password: admin
#    host: 192.168.6.66
#    port: 5672
#    virtual-host: /
#    publisher-returns: true # 发布者返回标志
#    publisher-confirm-type: simple #开启发布者简单确认机制
#    listener: #监听器帮我们(消费端)拿消息。默认自动ack
#      type: simple
#      simple:
#        acknowledge-mode: manual #开启手动确认机制 。除非程序员自己ack 否则服务器认为消息还为回复
#        batch-size: 12
app:
  ware-url: http://localhost:9001/




